\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{comment}
\usepackage{mathtools} % arrow with text on it
\usepackage[hyphens]{url}
\usepackage{float}
\usepackage[scaled=0.85]{sourcecodepro} % ttfamily
\DeclareGraphicsExtensions{.eps}
\usepackage{epstopdf} % convert EPS figures to PDF
\usepackage{enumitem} % better description environments
\usepackage{hyperref} % links in the PDF
\hypersetup{
	backref = true,
	pagebackref = true,
	colorlinks = true,
	linkcolor =  [rgb]{0.0,0.0,0.8},
	anchorcolor = [rgb]{0.0,0.0,0.8},
	citecolor = [rgb]{0.0,0.0,0.8},
	filecolor = [rgb]{0.0,0.0,0.8},
	urlcolor = [rgb]{0.0,0.0,0.8}}

\usepackage{balance} % balance columns

% Tables
\usepackage{booktabs}
\usepackage{cellspace} % add line breaks inside cell (\makecell{...})
\usepackage{tabularx}
\usepackage{multirow}
\usepackage{subcaption}
